name: Build KImageFormats
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

env:
  VCPKG_BINARY_SOURCES: 'clear;default,readwrite'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            vers: '5.15.2'
            arch: 'win32_msvc2019'
            buildArch: 'X86'
          - os: windows-2022
            vers: '5.15.2'
            arch: 'win64_msvc2019_64'

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ matrix.vers }}
          arch: ${{ matrix.arch }}

      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'd504de05dcd7b55df34976be1c824324ec6bca2b'

      - name: Build KImageFormats (just one big step for now)
        run: pwsh pwsh/buildkimageformats.ps1
        env:
          buildArch: ${{ matrix.buildArch }}

      - name: 'Upload Artifact'
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: kimageformats-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: kimageformats/output

      - name: 'Zip Artifact'
        if: github.ref == 'refs/heads/master'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: kimageformats/output/
          filename: "kimageformats-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}.zip"

      - name: 'Upload to continous release'
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'debug'
          files: kimageformats-*.zip
