name: Build QtApng
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2022
            vers: '5.15.2'
            arch: 'win32_msvc2019'
            buildArch: 'X86'
          - os: windows-2022
            vers: '5.15.2'
            arch: 'win64_msvc2019_64'

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ matrix.vers }}
          arch: ${{ matrix.arch }}

      - name: Build QtApng
        run: pwsh pwsh/buildapng.ps1
        env:
          buildArch: ${{ matrix.buildArch }}

      - name: 'Upload Artifact'
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: qtapng-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: QtApng/output

      - name: 'Zip Artifact'
        if: github.ref == 'refs/heads/master'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: QtApng/output/
          filename: "qtapng-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}.zip"

      - name: 'Upload to continous release'
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'cont'
          files:  qtapng-*.zip
